version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8

jobs:
  test_and_build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v3-dependencies-{{ checksum "package.json" }}
          - v3-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v3-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run lint
          command: npm run lint
      - run:
          name: Run unit tests
          command: npm test
      - run:
          name: Build the project
          command: npm run build
      - run:
          name: Run coverage
          command: npm run coverage
      - run:
          name: Upload coverage results
          command: npm run update-codecov
      - persist_to_workspace:
          root: ~/repo
          paths: .

  integration_test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v3-dependencies-{{ checksum "package.json" }}
            - v3-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v3-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run integration tests
          command: npm test-integration

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  test-build-deploy:
    jobs:
      - test_and_build
      - integration_test
      - deploy:
          requires:
            - test_and_build
            - integration_test
          filters:
            tags:
              only: /^v.*/
            branches:
              only:
                - /^v.*/